Adding new initContainer to archive node

diff --git a/helm/archive-node-gcp/templates/archive.yaml b/helm/archive-node-gcp/templates/archive.yaml
--- a/helm/archive-node-gcp/templates/archive.yaml
+++ b/helm/archive-node-gcp/templates/archive.yaml
@@ -43,15 +43,20 @@ spec:
       {{- end }}
       {{- if $.Values.mina.runtimeConfig.enabled }}
       - name: daemon-config
-        image: busybox:latest
-        command:
-          - wget
-          - -O
-          - /root/config/genesis_ledger.json
-          - {{ $.Values.mina.runtimeConfig.genesisLedgerURL }}
+        image: alpine:latest
+        command: ["/bin/sh", "-c"]
+        args:
+          - |
+            echo "Downloading genesis ledger:";
+            wget -O /root/config/genesis_ledger.json {{ $.Values.mina.runtimeConfig.genesisLedgerURL }};
+
+            echo "Replacing baked ledger with {{ $.Values.mina.runtimeConfig.genesisLedgerURL }}";
+            cp /root/config/genesis_ledger.json /root/.mina-config/daemon.json || echo "Failed to copy file. Check permissions or file existence.";
         volumeMounts:
           - name: {{ $.Release.Name }}-daemon-config-dir
             mountPath: /root/config
+          - name: config-dir
+            mountPath: /root/.mina-config/
       {{- end }}
       containers:
       {{- if .Values.archive.enableLocalDaemon }}
