Only check format on git hook

diff --git a/scripts/git_hooks/pre-commit b/scripts/git_hooks/pre-commit
--- a/scripts/git_hooks/pre-commit
+++ b/scripts/git_hooks/pre-commit
@@ -1,3 +1,7 @@
 #!/bin/bash
 make doc_diagrams
-make reformat
+make check-format
+if [ "$?" != 0 ]; then
+  echo '** REFUSING TO COMMIT: "$ make check-format" failed'
+  exit 1
+fi
