check if daemon still running, don't infinite loop

diff --git a/scripts/mina-verify-packaged-fork-config b/scripts/mina-verify-packaged-fork-config
--- a/scripts/mina-verify-packaged-fork-config
+++ b/scripts/mina-verify-packaged-fork-config
@@ -78,7 +78,7 @@ if [ ! -e "$workdir/keys/p2p" ]; then
     "$MINA_EXE" libp2p generate-keypair --privkey-path "$workdir/keys/p2p"
 fi
 
-echo "generating genesis ledgers ... (this may take a while)"
+echo "generating genesis ledgers ... (this may take a while)" >&2
 
 cp "$1" "$workdir/config.json"
 sed -i -e 's/"set_verification_key": "signature"/"set_verification_key": {"auth": "signature", "txn_version": "1"}/' "$workdir/config.json"
@@ -89,7 +89,7 @@ LEDGER_HASHES_JSON="$workdir/hashes.json" \
 GENESIS_TIMESTAMP=$(jq -r '.genesis.genesis_state_timestamp' "$PACKAGED_DAEMON_CONFIG") \
 "$CREATE_RUNTIME_CONFIG" > "$workdir/config-substituted.json"
 
-echo "exporting ledgers from running node ... (this may take a while)"
+echo "exporting ledgers from running node ... (this may take a while)" >&2
 
 # export the packaged ledgers in a way where we know which one is which
 function extract_ledgers() {
@@ -99,6 +99,10 @@ function extract_ledgers() {
     "$MINA_EXE" daemon --libp2p-keypair "$workdir/keys/p2p" --config-file "$config_file" --seed --genesis-ledger-dir "$ledger_dir" &
     
     while ! "$MINA_EXE" ledger export staged-ledger  | jq >"$json_prefix-staged.json"; do
+        if ! grep -qFx $(cat ~/.mina-config/.mina-lock) <(jobs -rp); then
+            echo "daemon died before exporting ledgers" >&2
+            exit 1
+        fi
         sleep 1m
     done
     
@@ -113,7 +117,7 @@ mv -t "$workdir/ledgers-backup" /var/lib/coda/*.tar.gz
 extract_ledgers "$workdir/config-substituted.json" "$workdir/ledgers" "$workdir/reference"
 mv -t /var/lib/coda "$workdir/ledgers-backup"/*
 
-echo "Performing final comparisons..."
+echo "Performing final comparisons..." >&2
 error=0
 
 result=$(jq --slurpfile a "$workdir/config-substituted.json" --slurpfile b "$PACKAGED_DAEMON_CONFIG" -n '
@@ -122,7 +126,7 @@ result=$(jq --slurpfile a "$workdir/config-substituted.json" --slurpfile b "$PAC
    $a[0].ledger.hash == $b[0].ledger.hash)')
 
 if [ "$result" != "true" ]; then
-    echo "Packaged config hashes in $PACKAGED_DAEMON_CONFIG not expected compared to $workdir/config-substituted.json"
+    echo "Packaged config hashes in $PACKAGED_DAEMON_CONFIG not expected compared to $workdir/config-substituted.json" >&2
     error=1
 fi
 
@@ -132,7 +136,7 @@ for file in "$workdir"/packaged-*.json; do
     name=${name#packaged-}
     
     if ! cmp "$file" "$workdir/reference-$name.json"; then
-        echo "Error: $file does not match reference"
+        echo "Error: $file does not match reference" >&2
         error=1
     fi
 done
@@ -151,15 +155,15 @@ for file in "$workdir"/ledgers/*.tar.gz; do
     $ldb_cmd --hex --db="$tardir/generated" scan > $workdir/generated.scan
 
     if ! cmp $workdir/generated.scan $workdir/packaged.scan || ! cmp $workdir/packaged.scan $workdir/web.scan; then
-        echo "Error: kvdb contents mismatch for $tarname"
+        echo "Error: kvdb contents mismatch for $tarname" >&2
         error=1
     fi
 done
 
 if [ $error -ne 0 ]; then
-    echo "Error: failed validation"
+    echo "Error: failed validation" >&2
     exit 1
 else
-    echo "Validation successful"
+    echo "Validation successful" >&2
     exit 0
 fi
