source_build_fallback needs to use stderr to be seen

diff --git a/scripts/mina-verify-packaged-fork-config b/scripts/mina-verify-packaged-fork-config
--- a/scripts/mina-verify-packaged-fork-config
+++ b/scripts/mina-verify-packaged-fork-config
@@ -37,22 +37,24 @@ fi
 source_build_fallback() {
     if [ ! -e "$1" ]; then
         if [ ! -e "$2" ]; then
-            echo "Error: not find useable $1 or $2"
+            echo "Error: not find useable $1 or $2" >&2
             exit 1
+        else
+            echo "$2"
         fi
     else
       echo "$1"
     fi
 }
 
-MINA_EXE=${MINA_EXE:-$(source_build_fallback mina ./_build/default/src/app/cli/src/mina.exe)}
-MINA_GENESIS_EXE=${MINA_GENESIS_EXE:-$(source_build_fallback mina-create-genesis ./_build/default/src/app/runtime_genesis_ledger/runtime_genesis_ledger.exe)}
-CREATE_RUNTIME_CONFIG=${CREATE_RUNTIME_CONFIG:-$(source_build_fallback mina-hf-create-runtime-config ./scripts/hardfork/create_runtime_config.sh)}
+MINA_EXE=${MINA_EXE:-$(source_build_fallback $(command -v mina) ./_build/default/src/app/cli/src/mina.exe)}
+MINA_GENESIS_EXE=${MINA_GENESIS_EXE:-$(source_build_fallback $(command -v mina-create-genesis) ./_build/default/src/app/runtime_genesis_ledger/runtime_genesis_ledger.exe)}
+CREATE_RUNTIME_CONFIG=${CREATE_RUNTIME_CONFIG:-$(source_build_fallback $(command -v mina-hf-create-runtime-config) ./scripts/hardfork/create_runtime_config.sh)}
 
 installed_config=$(echo /var/lib/coda/config_*.json)
 PACKAGED_DAEMON_CONFIG=${PACKAGED_DAEMON_CONFIG:-$installed_config}
-if [ ! -e "$found_config" ]; then
-    echo "Error: set PACKAGED_FORK_CONFIG to the path to the JSON file to verify"
+if [ ! -e "$installed_config" ]; then
+    echo "Error: set PACKAGED_DAEMON_CONFIG to the path to the JSON file to verify"
     exit 1
 fi
 
