slightly different approach
confirmed by testing ./mina-verify-packaged-fork-config and
observing:

    ember@hbox ~/d/mina (emberian-patch-3) [1]> ./scripts/mina-verify-packaged-fork-config devnet foo.json pwd
    Error: program not found in PATH (as mina-create-legacy-genesis) or relative to cwd (as ./runtime_genesis_ledger_of_mainnet.exe)

diff --git a/scripts/mina-verify-packaged-fork-config b/scripts/mina-verify-packaged-fork-config
--- a/scripts/mina-verify-packaged-fork-config
+++ b/scripts/mina-verify-packaged-fork-config
@@ -39,9 +39,10 @@ EOF
 fi
 
 source_build_fallback() {
-    if [ ! -x $(command -v "$1") ]; then
+    v=$(command -v "$1")
+    if [ ! -x "$v" ]; then
         if [ ! -x "$2" ]; then
-            echo "Error: program not found installed($1) or from source tree($2)" >&2
+            echo "Error: program not found in PATH (as $1) or relative to cwd (as $2)" >&2
             exit 1
         else
             echo "$2"
