friendlier script that compares the web ledger for good measure

diff --git a/scripts/mina-verify-packaged-fork-config b/scripts/mina-verify-packaged-fork-config
--- a/scripts/mina-verify-packaged-fork-config
+++ b/scripts/mina-verify-packaged-fork-config
@@ -12,10 +12,12 @@ Inputs:
 - The exported mainnet full config.json fork config, with all accounts
 - A working directory where ledgers/configs will be created
 - Installed MINA_EXE (default: mina) and MINA_GENESIS_EXE (default: mina-create-genesis) programs
-- PACKAGED_CONFIG_JSON (default: /var/lib/coda/config_*.json)
+- PACKAGED_DAEMON_CONFIG (default: /var/lib/coda/config_*.json)
   the runtime config generated by the HF packaging
+- CREATE_RUNTIME_CONFIG (default: mina-hf-create-runtime-config)
+  a copy of ./scripts/hardfork/create_runtime_config.sh
 - GENESIS_LEDGER_DIR (default: /var/lib/coda)
-  where the tarfiles are stored
+  where the tarfiles to verify are stored
 - FORKING_FROM_CONFIG_JSON (default: /var/lib/coda/mainnet.json)
   the pre-fork genesis ledger
 - SECONDS_PER_SLOT (default: 180)
@@ -32,17 +34,34 @@ EOF
     exit 1
 fi
 
-MINA_EXE=${MINA_EXE:-"mina"}
-MINA_GENESIS_EXE=${MINA_GENESIS_EXE:-"mina-create-genesis"}
-found_config=$(echo /var/lib/coda/config_*.json)
-PACKAGED_CONFIG_JSON=${PACKAGED_CONFIG_JSON:-$found_config}
-CREATE_RUNTIME_CONFIG=${CREATE_RUNTIME_CONFIG:-mina-hf-create-runtime-config}
-if [ ! -x "$CREATE_RUNTIME_CONFIG" ]; then
-    CREATE_RUNTIME_CONFIG=./scripts/hardfork/create_runtime_config.sh
+source_build_fallback() {
+    if [ ! -e "$1" ]; then
+        if [ ! -e "$2" ]; then
+            echo "Error: not find useable $1 or $2"
+            exit 1
+        fi
+    else
+      echo "$1"
+    fi
+}
+
+MINA_EXE=${MINA_EXE:-$(source_build_fallback mina ./_build/default/src/app/cli/src/mina.exe)}
+MINA_GENESIS_EXE=${MINA_GENESIS_EXE:-$(source_build_fallback mina-create-genesis ./_build/default/src/app/runtime_genesis_ledger/runtime_genesis_ledger.exe)}
+CREATE_RUNTIME_CONFIG=${CREATE_RUNTIME_CONFIG:-$(source_build_fallback mina-hf-create-runtime-config ./scripts/hardfork/create_runtime_config.sh)}
+
+installed_config=$(echo /var/lib/coda/config_*.json)
+PACKAGED_DAEMON_CONFIG=${PACKAGED_DAEMON_CONFIG:-$installed_config}
+if [ ! -e "$found_config" ]; then
+    echo "Error: set PACKAGED_FORK_CONFIG to the path to the JSON file to verify"
+    exit 1
 fi
+
+
 GENESIS_LEDGER_DIR=${GENESIS_LEDGER_DIR:-"/var/lib/coda"}
+
 SECONDS_PER_SLOT=${SECONDS_PER_SLOT:=180}
-export FORKING_FROM_CONFIG_JSON=${FORKING_FROM_CONFIG_JSON:=/var/lib/coda/mainnet.json}
+
+export FORKING_FROM_CONFIG_JSON=${FORKING_FROM_CONFIG_JSON:-$(source_build_fallback /var/lib/coda/mainnet.json genesis_ledgers/mainnet.json)}
 
 export MINA_LIBP2P_PASS=''
 
@@ -72,14 +91,17 @@ echo "exporting ledgers from running node ... (this may take a while)"
 
 # export the packaged ledgers in a way where we know which one is which
 function extract_ledgers() {
-    "$MINA_EXE" daemon --libp2p-keypair "$workdir/keys/p2p" --config-file "$1" --seed --genesis-ledger-dir "$2" &
+    config_file=$1
+    ledger_dir=$2
+    json_prefix=$3
+    "$MINA_EXE" daemon --libp2p-keypair "$workdir/keys/p2p" --config-file "$config_file" --seed --genesis-ledger-dir "ledger_dir" &
     
-    while ! "$MINA_EXE" ledger export staged-ledger  | jq >"$3-staged.json"; do
+    while ! "$MINA_EXE" ledger export staged-ledger  | jq >"$json_prefix-staged.json"; do
         sleep 1m
     done
     
-    "$MINA_EXE" ledger export staking-epoch-ledger | jq > "$3-staking.json"
-    "$MINA_EXE" ledger export next-epoch-ledger | jq > "$3-next.json"
+    "$MINA_EXE" ledger export staking-epoch-ledger | jq > "$json_prefix-staking.json"
+    "$MINA_EXE" ledger export next-epoch-ledger | jq > "$json_prefix-next.json"
     
     "$MINA_EXE" client stop
 }
@@ -107,21 +129,27 @@ for file in "$workdir"/packaged-*.json; do
     name=${name%.json}
     name=${name#packaged-}
     
-    if ! diff "$file" "$workdir/reference-$name.json"; then
+    if ! cmp "$file" "$workdir/reference-$name.json"; then
         echo "Error: $file does not match reference"
         error=1
     fi
 done
 
+ldb_cmd=$(command -v rocksdb-ldb || command -v rocksdb_ldb || command -v ldb)
 for file in "$workdir"/ledgers/*.tar.gz; do
-    tarname=$(basename "$file")
-    tarname=${tarname%.tar.gz}
-    mkdir "$workdir/ledgers/$tarname/packaged";
-    mkdir "$workdir/ledgers/$tarname/reference";
-    tar -xzf "$file" -C "$workdir/ledgers/$tarname/reference"
-    tar -xzf "$GENESIS_LEDGER_DIR/$tarname.tar.gz" -C "$workdir/ledgers/$tarname/packaged"
-    if ! "$MINA_EXE" internal kvdb eq --rocksdb-dir "$workdir/ledgers/$tarname/packaged" --rocksdb-dir "$workdir/ledgers/$tarname/reference"; then
-        echo "Tarfile kvdb contents mismatch for $tarname"
+    tarname=${$(basename "$file")%.tar.gz}
+    tardir="$workdir/ledgers/$tarname"
+    mkdir -p "$tardir/{packaged,generated}"
+    tar -xzf "$file" -C "$tardir/generated"
+    tar -xzf "$GENESIS_LEDGER_DIR/$tarname.tar.gz" -C "$tardir/packaged"
+    curl "https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/$tarname.tar.gz" | tar -xz -C "$tardir/web"
+
+    $ldb_cmd --hex --db="$tardir/packaged" scan > $workdir/packaged.scan
+    $ldb_cmd --hex --db="$tardir/web" scan > $workdir/web.scan
+    $ldb_cmd --hex --db="$tardir/generated" scan > $workdir/generated.scan
+
+    if ! cmp $workdir/generated.scan $workdir/packaged.scan || ! cmp $workdir/packaged.scan $workdir/web.scan; then
+        echo "Error: kvdb contents mismatch for $tarname"
         error=1
     fi
 done
